title: Willkommen
email: benedikt@schackenberg.com

# WICHTIG: Tabs-Collection auf Top-Level
collections:
  tabs:
    output: true

defaults:
  - scope:
      path: ""
      type: tabs
    values:
      layout: page
      order: 0

description: >
  Hallo und herzlich willkommen auf meiner privaten Webseite!
  Schön, dass du hier bist. Ich arbeite leidenschaftlich gerne mit dem Microsoft SQL Server – sei es Administration, Performance-Tuning oder moderne Cloud-Lösungen.
url: "https://schackenberg.com"   # korrekt: zwei Slashes
github:
  username: BenediktSchackenberg
social:
  name: B e N e Dikt Schackenberg
  links:
    - https://github.com/BenediktSchackenberg    
baseurl: ""                       # leer lassen, wenn Seite auf der Domainwurzel liegt

theme: jekyll-theme-chirpy
theme_mode: Auto
avatar: /assets/img/meta.png

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

include:
  - assets/keys/benedikt-schackenberg.asc

# (Optional) Theme-Feinheiten – korrekt auf Top-Level belassen:
theme_config:
  appearance: "auto"
  back_home_text: ".."
  date_format: "%Y-%m-%d"
  show_description: true
  lowercase_titles: true
